name: SSH Server
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://gist.githubusercontent.com/ViniciusFXavier/e9a83d6d2fe7b075096d699e20190d21/raw/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_PASS: ${{ secrets.USER_PASS }}

     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 1h
